### PR TITLE
implement parse_eval_data

### PR DESCRIPTION
**Pull request by yuki-mt**
change based on https://github.com/rekcurd/drucker/pull/20

- add example of `parse_eval_data` implementation
- separate `EvaluateDetail` into `EvaluateDetail` and `EvaluateData`

`parse_eval_data` will be used in [EvaluationResult](https://github.com/rekcurd/drucker-grpc-proto/blob/master/drucker.proto#L58) as well, and it will prevent loading all file data at once

### CODE REVIEW

**Comment by keigohtr** [comment]
Thank you for your improvement!
I will check it after https://github.com/rekcurd/drucker/pull/20 is approved.

**Comment by yuki-mt** [comment]
https://github.com/rekcurd/drucker-example/pull/7/commits/e1518884a91664481ee4d25c32ff87377fffb11a is change along with https://github.com/rekcurd/drucker/pull/20#discussion_r240948047

**Comment by keigohtr** [comment]
LGTM

**Review by keigohtr — APPROVED** [review]
https://github.com/rekcurd/drucker/pull/20 is confirmed.

**Pull request merged**
